services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absence-conge-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    env_file:
        - .env
    command: sh -c "php artisan migrate --force && apache2-foreground"

  db:
    image: postgres:16-alpine
    container_name: absence-conge-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: absence_conge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d absence_conge"]
      interval: 10s
      timeout: 5s
      retries: 5
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absence-conge-queue
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped

volumes:
  pgdata:
